/*
 * Candy Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BuyCandy201Response struct {
	Thanks string `json:"thanks,omitempty"`

	Change int32 `json:"change,omitempty"`
}
